# https://github.com/getredash/redash/wiki/Local-development-setup
services:
  # docker-compose run --rm server create_db
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "35000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: REDASH_COOKIE_SECRET
      REDASH_MAIL_SERVER: "smtp2http"
      REDASH_MAIL_DEFAULT_SENDER: "me@lehungio.com"
  
  worker:
    image: redash/redash:latest
    command: scheduler
    environment:
      QUEUES: "queries,scheduled_queries,celery"
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      WORKERS_COUNT: 2
      REDASH_MAIL_SERVER: "smtp2http"
      REDASH_MAIL_DEFAULT_SENDER: "me@lehungio.com"
  
  redis:
    image: redis:3.0-alpine

  postgres:
    # image: postgres:9.5.6-alpine
    image: pgautoupgrade/pgautoupgrade:latest
    ports:
    - "5432:5432"
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data